receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4321
        
exporters:
  debug:
    verbosity: detailed
  otlphttp:
    endpoint: http://jaeger:4318
  prometheus:
    endpoint: "collector:9464"

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlphttp]
    metrics: 
      receivers: [otlp]
      exporters: [prometheus]
