apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
  #namespace: opentelemetry
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          http:
            endpoint: 0.0.0.0:4321
    processors:
      tail_sampling:
        decision_wait: 10s
        num_traces: 100
        expected_new_traces_per_sec: 10
        policies:
          [
            {
              name: errors-policy,
              type: status_code,
              status_code: { status_codes: [ERROR] },
            },
            {
              name: latency-policy,
              type: latency,
              latency: { threshold_ms: 100},
            },
            {
              name: probability-policy,
              type: probabilistic,
              probabilistic: { sampling_percentage: 1.0 },
            }
          ]
    exporters:
      debug:
        verbosity: detailed
      otlphttp:
        endpoint: http://jaeger:4318
      prometheus:
        endpoint: "0.0.0.0:9464"
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [tail_sampling]
          exporters: [otlphttp]
        metrics:
          receivers: [otlp]
          exporters: [prometheus] 

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector
  #namespace: opentelemetry
  labels:
    app: collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collector
  template:
    metadata:
      labels:
        app: collector
    spec:
      containers:
      - name: collector-container
        image: otel/opentelemetry-collector-contrib:latest
        # command: ["otelcol"] # Replace with the binary name, if required
        args: [ "--config=/etc/otel/config.yaml" ]
        ports:
        - containerPort: 4321 # OTLP HTTP
        - containerPort: 9464
        volumeMounts:
        - name: config-volume
          mountPath: /etc/otel/
      volumes:
      - name: config-volume
        configMap:
          name: collector-config
--- 
apiVersion: v1
kind: Service
metadata:
  name: collector
  #namespace: opentelemetry
spec:
  selector:
    app: collector
  ports:
    - protocol: TCP
      port: 4321
      targetPort: 4321
      name: otlp-http
    - protocol: TCP
      port: 9464
      targetPort: 9464
      name: scrape