apiVersion: apps/v1
kind: Deployment
metadata:
  name: binary
  #namespace: opentelemetry
  labels:
    app: binary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: binary
  template:
    metadata:
      labels:
        app: binary
    spec:
      containers:
      - name: api-container
        image: momosuke07/binary:latest
        resources:
          limits:
            cpu: "1"
            memory: "256Mi"
          requests:
            cpu: "200m"
            memory: "128Mi"
        env:
        - name: METRICS_ENDPOINT
          value: http://collector:4321/v1/metrics
        - name: TRACES_ENDPOINT
          value: http://collector:4321/v1/traces
        ports:
        - containerPort: 8001