apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: opentelemetry
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger-container
        image: jaegertracing/all-in-one:latest
        ports:
        - containerPort: 4318
        - containerPort: 16686

---

apiVersion: v1
kind: Service
metadata:
  name: jaeger
  #namespace: opentelemetry
spec:
  selector:
    app: jaeger
  ports:
    - protocol: TCP
      port: 4318
      targetPort: 4318
      name: otlphttp
    - protocol: TCP
      port: 16686
      targetPort: 16686
      name: ui