services:
  iperf:
    container_name: iperf_server
    build:
      context: .
      dockerfile: iperf_server
    ports:
      - "5201:5201"

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "4317:4317"
      - "16686:16686"
    environment:
      COLLECTOR_OTLP_ENABLED: 1

  collector:
    container_name: collector
    image: otel/opentelemetry-collector:latest
    ports:
      - "4320:4320" # OTLP gRPC
      - "4321:4321" # OTLP HTTP
      - "9464:9464"
    volumes:
      - ./collector-config.yaml:/etc/otel/config.yaml
    command: ["--config=/etc/otel/config.yaml"]
    depends_on:
      - jaeger
      #- prometheus
  
  api:
    container_name: api_services
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - jaeger
      - iperf