services:
  # iperf:
  #   container_name: iperf_server
  #   build:
  #     context: .
  #     dockerfile: iperf_server
  #   ports:
  #     - "5201:5201"

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=changeme
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data"


  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "4318:4318"
      - "16686:16686"
    environment:
      COLLECTOR_OTLP_ENABLED: 1
      SPAN_STORAGE_TYPE: elasticsearch
      ES_SERVER_URLS: http://elasticsearch:9200
    depends_on:
      - elasticsearch

  collector:
    container_name: collector
    image: otel/opentelemetry-collector:latest
    ports:
      - "4320:4320" # OTLP gRPC
      - "4321:4321" # OTLP HTTP
      - "9464:9464"
    volumes:
      - ./collector-config.yaml:/etc/otel/config.yaml
    command: ["--config=/etc/otel/config.yaml"]
    depends_on:
      - jaeger
  
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    depends_on:
      - collector
    
  
  api:
    container_name: api_services
    volumes:
      - .\api.py:/app/api.py
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - collector
      - jaeger
      # - iperf
      - prometheus

  binary:
    container_name: binary
    volumes:
      - .\binary_search.py:/app/binary_search.py
    build:
      context: .
      dockerfile: DockerfileBinary
    ports:
      - "8001:8001"
    depends_on:
      - collector
      - jaeger
      # - iperf
      - prometheus

  register:
    container_name: register
    volumes:
      - .\register.py:/app/register.py
    build:
      context: .
      dockerfile: DockerfileRegister
    ports:
      - "8002:8002"
    depends_on:
      - collector
      - jaeger
      # - iperf
      - prometheus
volumes:
  elasticsearch-data:
    driver: local