apiVersion: batch/v1
kind: Job
metadata:
  name: script
spec:
  completions: 5
  parallelism: 5
  template:
    spec:
      containers:
      - name: script
        image: momosuke07/script:latest
      restartPolicy: Always
  backoffLimit: 4