apiVersion: batch/v1
kind: Job
metadata:
  name: script
spec:
  template:
    spec:
      containers:
      - name: script
        image: momosuke07/script:latest
      restartPolicy: Never
  backoffLimit: 4