apiVersion: batch/v1
kind: Job
metadata:
  name: script
  namespace: rmalves
spec:
  template:
    spec:
      containers:
        - name: script
          image: momosuke07/script:latest
      restartPolicy: Never