apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: rmalves
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api-container
        image: momosuke07/api:latest
        # resources:
        #   limits:
        #     cpu: "1"
        #     memory: "256Mi"
        #   requests:
        #     cpu: "200m"
        #     memory: "128Mi"
        env:
        - name: METRICS_ENDPOINT
          value: http://collector:4321/v1/metrics
        - name: TRACES_ENDPOINT
          value: http://collector:4321/v1/traces
        ports:
        - containerPort: 8000

---

apiVersion: v1  
kind: Service
metadata:
  name: api
  namespace: rmalves
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000